const CONFIG = {
    titleWeb: "Thi thật tốt nhe",
    introTitle: 'Crush',
    introDesc: `Wishing you luck and success in your recent exam!`,
    btnIntro: '^^HiHi^^',
    title: 'Bí quyest để thi thật tốt🥰',
    desc: 'Phải thật bình tĩnh, tự tin, à nhớ ôn bài nữa.. Đặc biệt là đọc được cái nàyyy ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Thi xong thì liệu bạn có suy nghĩ thêm về chuyện tìm hiểu tuii hemmmmm',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Cái này thì chắc để từ từ... Xin lỗi bạn nha',
    mess: 'Mình biết mà 🥰. Không saoooo tui chờ được 😘😘',
    messDesc: 'Đọc xong thì chuẩn bị đi ngủ sớm  để mai thật sự tỉnh táo nha.',
    btnAccept: 'Okiiiii lun <3',
  }
